### ISSUE TITLE
1.18.1 update

### ISSUE THREAD

**Issue by EGOIST1372** [PheonixVX/MoreFlowerPots#4]
thanks in advance

**Comment by EGOIST1372** [comment]
we got 1.19 hurrayyyy
so I guess 1.18.2 is pointless at this point :D

**Comment by Joniator** [comment]
For everyone else looking for a 1.18.1 jar.
I updated it for a 1.18 modpack I use: https://github.com/Joniator/MoreFlowerPots-1.18-Port/releases/tag/2.0-SNAPSHOT-1.18.1

Its only tested with The Afterlife Modpack, targeted versions are found in the release

**Comment by PhoenixVX** [comment]
Updated to 1.19.3
